extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/Eletrobras
      name: Eletrobras no Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/eletrobrasoficial/
      name: Eletrobras no Instagram
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/eletrobras
      name: Eletrobras no LinkedIn
    - icon: fontawesome/brands/soundcloud
      link: https://soundcloud.com/podcasteletrobras
      name: Eletrobras no SoundCloud
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/EletrobrasEnergia
      name: Eletrobras no YouTube
    - icon: fontawesome/brands/x-twitter 
      link: https://twitter.com/Eletrobras
      name: Eletrobras no Twitter
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
nav:
  - Home: 'index.md'
  - 'Especificações Resumidas':
    - 'Chesf': 'resumos/chesf.md'
    - 'Eletronorte': 'resumos/eletronorte.md'
    - 'Eletrosul': 'resumos/eletrosul.md'
    - 'Furnas': 'resumos/furnas.md'
  - 'Taxonomia': 'taxonomia.md'
  - 'Instruções':
    - 'Uso do markdown': 'resumo_md.md'
plugins:
  - search
repo_url: https://github.com/danielpiupiu/GED-project
site_name: GED Eletrobras
site_url: https://não_esqueca_de_alterar_a_url.com/
theme:
  name: material
  logo: img/brasao_GED.png
  favicon: img/brasao_GED.png
  icon:
    repo: fontawesome/brands/github
  language: pt-BR
  features:
  - content.tabs.link
  - navigation.footer
  - navigation.path
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: lime
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: green